### PR TITLE
KlusacekJserver connect enhancement Issue #304

### PR DESCRIPTION
**Pull request by Sacek073**
# Description

This PR includes the enhancement from issue https://github.com/Dlubal-Software/RFEM_Python_Client/issues/304. It is possible that this could possibly break usage for some users, since some variables from initModel are moved to specific module. The logic of connecting to server is moved to a function, so it is not automatically runned on import of the module. All test are passing (some of them needed to be adjusted). Maybe we should discuss this enhancement before it is merged, but i think that it is needed anyway.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.04.007.274.cab2adb35e1
* Python version: 3.10.4

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by OndraMichal — APPROVED** [review]
The only point I have is the naming of the **globalsEnhancement**. Other than that nice work. I never thought that the automatic connection would be an issue, but it makes sense.

**Comment by Sacek073** [comment]
Yeah, the name **globalsEnhancement** is temporary placeholer, I don't know whoat would be the good name for this. Maybe something like **connectionGlobals**.

**Comment by OndraMichal** [comment]
Change it to connectionGlobals. That is OK.

**Review by OndraMichal — APPROVED** [review]
Was not able to check via remote connection.

**Pull request merged**
