### PR TITLE
Ondrej Michal: TankWebApp update

### PR DESCRIPTION
**Pull request by OndraMichal**
# Description

All result files of the example are removed from source code and put to ignore list.
.vtk file can be put into /export folder with .vtp file in /export/export folder.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [x] Attached examples

**Test Configuration**:
* RFEM version: .02.0037.102.3c6df58020c
* Python version: 3.10.6

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dogukankaratas** [comment]
I deleted the export.obj and export.mtl files in the main directory and still works fine. I think we don't need them in the first place.

**Comment by OndraMichal** [comment]
Heet Rojivadiya
02.11 9:231
Hello, I made new obj and vtp files on PR because the default shape of tank is not looking good. and the calculate button is static. so, I change the button effect in css. And change position of the html component from px to % in .css so screen size won't effect on layout. If you run tankWebApp.py when any other model is open then it gives error. Therefor, I did minor chnage in responsiveTank.py. These are the main reasons behind the new PR.

**Comment by dogukankaratas** [comment]
Since we changed the file order, the initial page does not show any 3D rendering. I prefer to have an initial file and a VTK rendering in the initial state of the program.

Can we put the default obj files under the folder TankWebApp?
image

**Comment by dogukankaratas** [comment]
I just pushed my recommended changes (extra small). Can you check it? After that it's ready to merge I think.

**Review by dogukankaratas — APPROVED** [review]

**Pull request merged**
