### PR TITLE
Ondrej Michal-result tables

### PR DESCRIPTION
**Pull request by OndraMichal**
Based of US-3941 there are new functions available to get result tables.
Also added are functions like GetMinValue, GetMaxValue, GetResultTableParameters to get all parameters in the table and ConvertResultsToListOfDct to change the data to more suitable list of dictionaries. One dict corresponds to one line in table.

Note: 
It was taken into account that there are still texts where numbers should be and some flexibility in number of parameters in each line is also there.

For testing use installation Team9\US-3941_b158396_a0e8a16f6d5.
Issue #78

### CODE REVIEW

**Comment by dogukankaratas** [comment]
1 test failed:
image

**Comment by dogukankaratas** [comment]
About the architecture; I suggest to split modules -I'd rather to have every module under 1000 line-. 

We can have a base class, in this case ResultTables(), and inherit some functions from other modules. For example; we can have a file named modalAnalysisResults.py which contains a class named ModalAnalysisResults(). And then we can inherite this class in ResultTables() class. 

It would be easiser to maintain in my opinion.

**Comment by OndraMichal** [comment]
> 1 test failed: image

Hi,
you crearly tested older version. Try the latest one (a5c9abeddaa7e6a4c18d984500445fe8766fba9c). The issue should be resolved.

**Comment by OndraMichal** [comment]
> 

All 258 have same structure and logic, hence the naintanance is very easy even in +4000 lines file. Easy to do same change in all methods. The maintanance could be done across multiple files, no doubt, but scope of Find must be well defined.

Divinding it into categories/classes can be done but I can't imagine what the categories would be named. If it should be divided according name, then we end up with some files/classes having 20 methods and many of them having just 1. That adds to complexity in my mind. We could end up with 40 - 50 subcategories. If we assume that those have to be also imported at the beginning of the file, not everybody could find this straight forward. Dividing it into 4 sub 1000 line files bring the challenge of naming them logically. What do you think?

**Comment by dogukankaratas** [comment]
Tests are passing with the latest commit. Acc. to file architecture, let's leave it as it is for quick publishing for now. Maybe we can discuss it later deeply 👍🏻

**Review by dogukankaratas — APPROVED** [review]

**Pull request merged**
